### ISSUE TITLE
Add option to set class on `picture`

### ISSUE THREAD

**Issue by florianbrinkmann** [visuellverstehen/statamic-picturesque#12]
Currently it’s not possible to add the `class` attr of the `picture` element. Sometimes that’s needed, if one doesn’t want to wrap the `picture` call into another wrapper like a `figure`. I’d suggest something like a `wrapper_class` attribute.

**Comment by simonolog** [comment]
Have a look at #6, mate 😁

**Comment by florianbrinkmann** [comment]
oh 😅 🙈
