### ISSUE TITLE
Ability to apply the focal point without cropping

### ISSUE THREAD

**Issue by kobe-f8** [visuellverstehen/statamic-picturesque#16]
I was wondering if it's possible to apply the focal point set by the user without needing to crop the image. I've had multiple instances where this is the case. 

In the past I did this when I was using a picture partial:
```
{{ if cover }}
    class="object-cover w-full h-full {{ class }}"
    style="object-position: {{ focus | background_position }}"
{{ /if }}
```

Maybe a cool feature in general for the future could by to add styles?

**Comment by simonolog** [comment]
That's a neat idea! 😃 

As it's quite specific, I think for now we will add the possibility to add things to the `style` attribute (in the same way as with the `class` attribute), so you can add your custom logic using the focus.
