### ISSUE TITLE
Add support for `picture` classes

### ISSUE THREAD

**Issue by florianbrinkmann** [visuellverstehen/statamic-picturesque#6]
Currently it is not possible to add classes to the `picture` element, but that could be helpful sometimes. Maybe we could add something like a `wrapper_class` attribute to the tag.

**Comment by simonolog** [comment]
@florianbrinkmann Yep, good idea!

Resolved in b5890d1ca19a130e6a11ed97dadf82f05eaa8ffe and released in [v1.4.0](https://github.com/visuellverstehen/statamic-picturesque/releases/tag/v1.4.0).
