### ISSUE TITLE
Is it possible to generate multiple filetypes? Like webp and png for example

### ISSUE THREAD

**Issue by kobe-f8** [visuellverstehen/statamic-picturesque#7]

**Comment by simonolog** [comment]
@kobe-f8 We had this on our todo list for a while but up until now never had an occasion to add this. So, thanks for the kick in the backside ;) 

Resolved in dde8790154eb420b45145cd90159823992b150ae and released in [v1.4.0](https://github.com/visuellverstehen/statamic-picturesque/releases/tag/v1.4.0).
