### ISSUE TITLE
After updating to version 1.4 aspect ratio cropping stopped working

### ISSUE THREAD

**Issue by kobe-f8** [visuellverstehen/statamic-picturesque#8]
Reverting back to version 1.3 fixes the problem

**Comment by simonolog** [comment]
Thank you, fixed this in [1.4.1](https://github.com/visuellverstehen/statamic-picturesque/releases/tag/v1.4.1). Also works as a good reminder to finally add tests to this package 🙈

**Comment by kobe-f8** [comment]
Thank you for fixing it so quickly! <3
